### ISSUE TITLE
not able to "Clear all cache" in Install-Tool

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/typo3-cms-speciality-distribution#99]
I used as suggested the Settings.php for Database-Connection. Frontend and Backend works fine, but if i want to "clear all Cache" in important actions in Install-Tool i get 
```Detected Fatal Error
Uncaught exception 'RuntimeException' with message 'TYPO3 Fatal Error: No database selected!' in /home/www/TYPO3.src/typo3/sysext/core/Classes/Database/DatabaseConnection.php:1563 Stack trace: #0 /home/www/TYPO3.src/typo3/sysext/install/Classes/Service/ClearCacheService.php(116): TYPO3\CMS\Core\Database\DatabaseConnection->connectDB() #1 /home/www/TYPO3.src/typo3/sysext/install/Classes/Service/ClearCacheService.php(67): TYPO3\CMS\Install\Service\ClearCacheService->getDatabaseConnection() #2 /home/www/TYPO3.src/typo3/sysext/install/Classes/Controller/Action/Tool/ImportantActions.php(162): TYPO3\CMS\Install\Service\ClearCacheService->clearAll() #3 /home/www/TYPO3.src/typo3/sysext/install/Classes/Controller/Action/Tool/ImportantActions.php(57): TYPO3\CMS\Install\Controller\Action\Tool\ImportantActions->clearAllCache() #4 /home/www/TYPO3.src/typo3/sysext/install/Classes/Controller/Action/AbstractAction.php(99): TYPO3\CMS\Install\Controller\Action\Tool\ImportantActions->executeAction() #5 /home/www/TYPO3.src/typo3 in /home/www/TYPO3.src/typo3/sysext/core/Classes/Database/DatabaseConnection.php on line 1563```

If I move the DB-Data in LocalConfiguration everything works fine.

**Comment by fabarea** [comment]
Should be fixed by now.
